version: '3.3'

services:
  # Main application database.
  app_db:
    image: mysql
    volumes:
      - db_data
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  # Capture and display all email sent by WordPress.
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  # Main application service
  testable_app:
    image: wpgraphql/wordpress:${WORDPRESS_IMAGE_VERSION:-latest}
    depends_on:
      - app_db
      - mailhog
    build: .
    volumes:
      - .:/var/www/html/wp-content/plugins/wp-graphql
      - ./local/public:/var/www/html # WP core files.
      - ./local/.htaccess:/var/www/html/.htaccess
      - ./tests:/var/www/html/tests
      - ./codeception.dist.yml:/var/www/html/codeception.yml
    env_file: .env.dist
    environment:
      APACHE_RUN_USER: "#1000" # Ensure Apache can write to the filesystem.
      XDEBUG_CONFIG: remote_host=10.0.0.120 idekey=vscode
      WPGRAPHQL_AUTOLOAD: 1
    ports:
      - 8080:80

  # Main application database clone for testing inside the main application service.
  testing_db:
    image: mysql
    volumes:
      - ./local/db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  # Standalone testing application
  run_tests:
    image: wpgraphql/wordpress:${WORDPRESS_IMAGE_VERSION:-latest}
    depends_on:
      - testing_db
    build:
      context: .
      args:
        PHPUNIT_VERSION: ${PHPUNIT_VERSION:-:<=9.4.4}
        PHP_VERSION: ${PHP_VERSION:-7.4}
    volumes:
      - .:/var/www/html/wp-content/plugins/wp-graphql
      - ./local/public:/var/www/html # WP core files.
      - ./local/.htaccess:/var/www/html/.htaccess
      - ./tests:/var/www/html/tests
      - ./codeception.dist.yml:/var/www/html/codeception.yml
    env_file: .env.dist
    environment:
      APACHE_RUN_USER: "#1000" # Ensure Apache can write to the filesystem.
      DB_HOST: testing_db
      WPGRAPHQL_AUTOLOAD: 1
    command: ./setup-database.sh testing codecept run ${FILTER:-}
    ports:
      - 8080:80
volumes:
  db_data: {}
